AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  StageName:
    Type: String
    Default: Prod
    
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "follow_lambda"
      CodeUri: hello-world/
      InlineCode: |
          exports.lambdaHandler = async (event, context) => {
            let response;
            try {
                response = {
                    'statusCode': 200,
                    'body': JSON.stringify({
                        message: 'hello world 1'
                    })
                }
            } catch (err) {
                return err;
            }
            return response
          };
      Handler: app.handler
      Runtime: nodejs14.x
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /hello
            TimeoutInMillis: 15000
            PayloadFormatVersion: "2.0"
            RouteSettings:
              ThrottlingBurstLimit: 600
  
  firstlambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "flirt_lambda"
      InlineCode: |
          exports.lambdaHandler = async (event, context) => {
            let response;
            try {
                response = {
                    'statusCode': 200,
                    'body': JSON.stringify({
                        message: 'hello guna'
                    })
                }
            } catch (err) {
                return err;
            }
            return response
          };
      Handler: app.handler
      Runtime: nodejs14.x
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /guna
            TimeoutInMillis: 15000
            PayloadFormatVersion: "1.0"
            RouteSettings:
              ThrottlingBurstLimit: 600
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      Tags:
        Tag: Value
      AccessLogSettings:
        DestinationArn: !GetAtt AccessLogs.Arn
        Format: $context.requestId
      DefaultRouteSettings:
        ThrottlingBurstLimit: 200
      RouteSettings:
        "GET /hello":
          ThrottlingBurstLimit: 500 # overridden in HttpApi Event
      StageVariables:
        StageVar: Value
      FailOnWarnings: true

  AccessLogs:
    Type: AWS::Logs::LogGroup

Outputs:
  HttpApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/'
  HttpApiId:
    Description: Api id of HttpApi
    Value:
      Ref: HttpApi

